import React, { useState } from 'react';
import {
    StyleSheet,
    Text,
    View,
    ScrollView,
    TouchableOpacity,
    Modal,
    TextInput,
    Alert,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
// Address type now imported from context
import { useAddresses, Address } from '@/contexts/AddressContext';
import { useNotifications } from '@/contexts/NotificationContext';
import { useTheme } from '@/contexts/ThemeContext';

export default function AddressesScreen() {
    const router = useRouter();
    const insets = useSafeAreaInsets();
    const { unreadCount } = useNotifications();
    const { addresses, addAddress, updateAddress, deleteAddress } = useAddresses();
    const { isDark } = useTheme();

    const [selectedAddress, setSelectedAddress] = useState<Address | null>(null);
    const [showMenu, setShowMenu] = useState(false);
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
    const [showAddressForm, setShowAddressForm] = useState(false);
    const [isEditing, setIsEditing] = useState(false);

    // Form state
    const [formData, setFormData] = useState({
        type: '',
        address: '',
        city: '',
        pincode: '',
        landmark: '',
        receiverName: '',
        receiverPhone: '',
    });

    const handleMenuPress = (address: Address) => {
        setSelectedAddress(address);
        setShowMenu(true);
    };

    const handleEdit = () => {
        if (selectedAddress) {
            setFormData({
                type: selectedAddress.type,
                address: selectedAddress.address,
                city: selectedAddress.city,
                pincode: selectedAddress.pincode || '',
                landmark: selectedAddress.landmark || '',
                receiverName: selectedAddress.receiverName || '',
                receiverPhone: selectedAddress.receiverPhone || '',
            });
            setIsEditing(true);
            setShowMenu(false);
            setShowAddressForm(true);
        }
    };

    const handleDelete = () => {
        setShowMenu(false);
        setShowDeleteConfirm(true);
    };

    const confirmDelete = () => {
        if (selectedAddress) {
            deleteAddress(selectedAddress.id);
            setShowDeleteConfirm(false);
            setSelectedAddress(null);
        }
    };

    const handleAddNew = () => {
        setFormData({
            type: '',
            address: '',
            city: '',
            pincode: '',
            landmark: '',
            receiverName: '',
            receiverPhone: '',
        });
        setIsEditing(false);
        setShowAddressForm(true);
    };

    const handleSaveAddress = async () => {
        if (!formData.type || !formData.address || !formData.city) {
            Alert.alert('Error', 'Please fill in all required fields');
            return;
        }

        try {
            if (isEditing && selectedAddress) {
                // Update existing address
                await updateAddress(selectedAddress.id, formData);
            } else {
                // Add new address - ID is generated by DB
                const newAddressData = {
                    icon: getIconForType(formData.type),
                    ...formData,
                };
                await addAddress(newAddressData);
            }
            setShowAddressForm(false);
            setSelectedAddress(null);
        } catch (error) {
            // Error handling is mostly done in context, but we catch here to be safe
            console.error(error);
        }
    };

    const getIconForType = (type: string): string => {
        const lowerType = type.toLowerCase();
        if (lowerType.includes('home')) return 'home-outline';
        if (lowerType.includes('office') || lowerType.includes('work')) return 'briefcase-outline';
        if (lowerType.includes('cafe') || lowerType.includes('coffee')) return 'cafe-outline';
        return 'location-outline';
    };

    return (
        <View style={[styles.container, { paddingTop: insets.top + 10 }, isDark && { backgroundColor: '#121212' }]}>
            <StatusBar style={isDark ? "light" : "dark"} />

            {/* Header */}
            <View style={[styles.header, isDark && { backgroundColor: '#121212', borderBottomColor: '#333' }]}>
                <TouchableOpacity onPress={() => router.back()} style={[styles.iconButton, isDark && { backgroundColor: '#333' }]}>
                    <Ionicons name="arrow-back" size={24} color={isDark ? '#FFF' : '#1A1A1A'} />
                </TouchableOpacity>
                <Text style={[styles.headerTitle, isDark && { color: '#FFF' }]}>Addresses</Text>
                <TouchableOpacity
                    style={[styles.notificationBtn, isDark && { backgroundColor: '#333' }]}
                    onPress={() => router.push('/notifications')}
                >
                    <Ionicons name="notifications-outline" size={24} color={isDark ? '#FFF' : '#1A1A1A'} />
                    {unreadCount > 0 && (
                        <View style={styles.notificationBadge}>
                            <Text style={styles.badgeText}>{unreadCount}</Text>
                        </View>
                    )}
                </TouchableOpacity>
            </View>

            <ScrollView
                contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 20 }]}
                showsVerticalScrollIndicator={false}
            >
                {/* My Addresses Section */}
                <Text style={[styles.sectionTitle, isDark && { color: '#FFF' }]}>My Addresses</Text>

                {addresses.map((item) => (
                    <TouchableOpacity
                        key={item.id}
                        style={[styles.addressCard, isDark && { backgroundColor: '#1E1E1E', borderColor: '#333' }]}
                        activeOpacity={0.7}
                    >
                        <View style={styles.addressContent}>
                            <View style={[styles.iconContainer, isDark && { backgroundColor: '#333' }]}>
                                <MaterialCommunityIcons
                                    name={item.icon as any}
                                    size={24}
                                    color={isDark ? '#FFF' : '#1A1A1A'}
                                />
                            </View>
                            <View style={styles.addressInfo}>
                                <Text style={[styles.addressType, isDark && { color: '#FFF' }]}>{item.type}</Text>
                                <Text style={[styles.addressText, isDark && { color: '#AAA' }]} numberOfLines={2}>
                                    {item.address}
                                </Text>
                                <Text style={[styles.addressCity, isDark && { color: '#888' }]}>{item.city}</Text>
                            </View>
                        </View>
                        <TouchableOpacity
                            style={styles.moreButton}
                            onPress={() => handleMenuPress(item)}
                        >
                            <Ionicons name="ellipsis-horizontal" size={20} color={isDark ? '#FFF' : '#1A1A1A'} />
                        </TouchableOpacity>
                    </TouchableOpacity>
                ))}

                {/* Add Address Section */}
                <Text style={[styles.sectionTitle, isDark && { color: '#FFF' }]}>Add Address</Text>

                <TouchableOpacity
                    style={[styles.addAddressCard, isDark && { backgroundColor: '#1E1E1E', borderColor: '#333' }]}
                    activeOpacity={0.7}
                    onPress={handleAddNew}
                >
                    <View style={styles.addressContent}>
                        <View style={[styles.iconContainer, isDark && { backgroundColor: '#333' }]}>
                            <Ionicons name="add" size={24} color={isDark ? '#FFF' : '#1A1A1A'} />
                        </View>
                        <View style={styles.addressInfo}>
                            <Text style={[styles.addressType, isDark && { color: '#FFF' }]}>Add New Address</Text>
                            <Text style={[styles.addressSubtext, isDark && { color: '#AAA' }]}>
                                Like, Home, Work, Office, etc
                            </Text>
                        </View>
                    </View>
                    <TouchableOpacity style={styles.moreButton}>
                        <Ionicons name="ellipsis-horizontal" size={20} color={isDark ? '#FFF' : '#1A1A1A'} />
                    </TouchableOpacity>
                </TouchableOpacity>
            </ScrollView>

            {/* Menu Modal */}
            <Modal
                visible={showMenu}
                transparent
                animationType="fade"
                onRequestClose={() => setShowMenu(false)}
            >
                <TouchableOpacity
                    style={styles.modalOverlay}
                    activeOpacity={1}
                    onPress={() => setShowMenu(false)}
                >
                    <View style={[styles.menuModal, isDark && { backgroundColor: '#1E1E1E' }]}>
                        <TouchableOpacity style={styles.menuItem} onPress={handleEdit}>
                            <Ionicons name="create-outline" size={20} color={isDark ? '#FFF' : '#1A1A1A'} />
                            <Text style={[styles.menuText, isDark && { color: '#FFF' }]}>Edit</Text>
                        </TouchableOpacity>
                        <View style={[styles.menuDivider, isDark && { backgroundColor: '#333' }]} />
                        <TouchableOpacity style={styles.menuItem} onPress={handleDelete}>
                            <Ionicons name="trash-outline" size={20} color="#FF4B4B" />
                            <Text style={[styles.menuText, { color: '#FF4B4B' }]}>Delete</Text>
                        </TouchableOpacity>
                    </View>
                </TouchableOpacity>
            </Modal>

            {/* Delete Confirmation Modal */}
            <Modal
                visible={showDeleteConfirm}
                transparent
                animationType="fade"
                onRequestClose={() => setShowDeleteConfirm(false)}
            >
                <View style={styles.modalOverlay}>
                    <View style={[styles.confirmModal, isDark && { backgroundColor: '#1E1E1E' }]}>
                        <Text style={[styles.confirmTitle, isDark && { color: '#FFF' }]}>Delete Address?</Text>
                        <Text style={[styles.confirmText, isDark && { color: '#AAA' }]}>
                            Are you sure you want to delete this address?
                        </Text>
                        <View style={styles.confirmButtons}>
                            <TouchableOpacity
                                style={[styles.cancelButton, isDark && { backgroundColor: '#333' }]}
                                onPress={() => setShowDeleteConfirm(false)}
                            >
                                <Text style={[styles.cancelButtonText, isDark && { color: '#FFF' }]}>Cancel</Text>
                            </TouchableOpacity>
                            <TouchableOpacity
                                style={styles.deleteButton}
                                onPress={confirmDelete}
                            >
                                <Text style={styles.deleteButtonText}>Delete</Text>
                            </TouchableOpacity>
                        </View>
                    </View>
                </View>
            </Modal>

            {/* Add/Edit Address Form Modal */}
            <Modal
                visible={showAddressForm}
                animationType="slide"
                onRequestClose={() => setShowAddressForm(false)}
            >
                <View style={[styles.formContainer, { paddingTop: insets.top + 10 }, isDark && { backgroundColor: '#121212' }]}>
                    <View style={[styles.formHeader, isDark && { borderBottomColor: '#333' }]}>
                        <TouchableOpacity onPress={() => setShowAddressForm(false)}>
                            <Ionicons name="close" size={24} color={isDark ? '#FFF' : '#1A1A1A'} />
                        </TouchableOpacity>
                        <Text style={[styles.formTitle, isDark && { color: '#FFF' }]}>
                            {isEditing ? 'Edit Address' : 'Add New Address'}
                        </Text>
                        <View style={{ width: 24 }} />
                    </View>

                    <ScrollView
                        style={styles.formScroll}
                        contentContainerStyle={{ paddingBottom: insets.bottom + 20 }}
                    >
                        <View style={styles.formField}>
                            <Text style={[styles.formLabel, isDark && { color: '#FFF' }]}>Address Type *</Text>
                            <TextInput
                                style={[styles.formInput, isDark && { backgroundColor: '#333', borderColor: '#444', color: '#FFF' }]}
                                placeholder="e.g., Home, Office, Work"
                                placeholderTextColor={isDark ? '#888' : '#999'}
                                value={formData.type}
                                onChangeText={(text) => setFormData({ ...formData, type: text })}
                            />
                        </View>

                        <View style={styles.formField}>
                            <Text style={[styles.formLabel, isDark && { color: '#FFF' }]}>Full Address *</Text>
                            <TextInput
                                style={[styles.formInput, styles.textArea, isDark && { backgroundColor: '#333', borderColor: '#444', color: '#FFF' }]}
                                placeholder="House/Flat No., Street, Area"
                                placeholderTextColor={isDark ? '#888' : '#999'}
                                value={formData.address}
                                onChangeText={(text) => setFormData({ ...formData, address: text })}
                                multiline
                                numberOfLines={3}
                            />
                        </View>

                        <View style={styles.formField}>
                            <Text style={[styles.formLabel, isDark && { color: '#FFF' }]}>City/Town *</Text>
                            <TextInput
                                style={[styles.formInput, isDark && { backgroundColor: '#333', borderColor: '#444', color: '#FFF' }]}
                                placeholder="Enter city or town"
                                placeholderTextColor={isDark ? '#888' : '#999'}
                                value={formData.city}
                                onChangeText={(text) => setFormData({ ...formData, city: text })}
                            />
                        </View>

                        <View style={styles.formField}>
                            <Text style={[styles.formLabel, isDark && { color: '#FFF' }]}>Pincode</Text>
                            <TextInput
                                style={[styles.formInput, isDark && { backgroundColor: '#333', borderColor: '#444', color: '#FFF' }]}
                                placeholder="Enter pincode"
                                placeholderTextColor={isDark ? '#888' : '#999'}
                                value={formData.pincode}
                                onChangeText={(text) => setFormData({ ...formData, pincode: text })}
                                keyboardType="numeric"
                            />
                        </View>

                        <View style={styles.formField}>
                            <Text style={[styles.formLabel, isDark && { color: '#FFF' }]}>Landmark (Optional)</Text>
                            <TextInput
                                style={[styles.formInput, isDark && { backgroundColor: '#333', borderColor: '#444', color: '#FFF' }]}
                                placeholder="Nearby landmark"
                                placeholderTextColor={isDark ? '#888' : '#999'}
                                value={formData.landmark}
                                onChangeText={(text) => setFormData({ ...formData, landmark: text })}
                            />
                        </View>

                        <Text style={[styles.sectionTitle, { paddingHorizontal: 20, marginTop: 20, marginBottom: 10 }, isDark && { color: '#FFF' }]}>Receiver Details (Optional)</Text>

                        <View style={styles.formField}>
                            <Text style={[styles.formLabel, isDark && { color: '#FFF' }]}>Receiver Name</Text>
                            <TextInput
                                style={[styles.formInput, isDark && { backgroundColor: '#333', borderColor: '#444', color: '#FFF' }]}
                                placeholder="e.g. Someone Else"
                                placeholderTextColor={isDark ? '#888' : '#999'}
                                value={formData.receiverName}
                                onChangeText={(text) => setFormData({ ...formData, receiverName: text })}
                            />
                        </View>

                        <View style={styles.formField}>
                            <Text style={[styles.formLabel, isDark && { color: '#FFF' }]}>Receiver Phone</Text>
                            <TextInput
                                style={[styles.formInput, isDark && { backgroundColor: '#333', borderColor: '#444', color: '#FFF' }]}
                                placeholder="e.g. 9876543210"
                                placeholderTextColor={isDark ? '#888' : '#999'}
                                value={formData.receiverPhone}
                                onChangeText={(text) => setFormData({ ...formData, receiverPhone: text })}
                                keyboardType="phone-pad"
                                maxLength={10}
                            />
                        </View>

                        <TouchableOpacity
                            style={styles.saveButton}
                            onPress={handleSaveAddress}
                        >
                            <Text style={styles.saveButtonText}>
                                {isEditing ? 'Update Address' : 'Save Address'}
                            </Text>
                        </TouchableOpacity>
                    </ScrollView>
                </View>
            </Modal>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FAFAFA',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingBottom: 20,
        backgroundColor: '#fff',
    },
    headerTitle: {
        fontSize: 18,
        fontFamily: 'DMSans_700Bold',
        color: '#1A1A1A',
    },
    iconButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        borderRadius: 20,
    },
    notificationBtn: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    notificationBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: '#1F5E2E',
        borderRadius: 8,
        width: 16,
        height: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: '#fff',
    },
    badgeText: {
        color: '#fff',
        fontSize: 9,
        fontFamily: 'DMSans_700Bold',
        lineHeight: 10,
    },
    content: {
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontFamily: 'DMSans_700Bold',
        color: '#1A1A1A',
        marginBottom: 16,
        marginTop: 8,
    },
    addressCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E8E8E8',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    addAddressCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E8E8E8',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    addressContent: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        flex: 1,
    },
    iconContainer: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    addressInfo: {
        flex: 1,
    },
    addressType: {
        fontSize: 16,
        fontFamily: 'DMSans_700Bold',
        color: '#1A1A1A',
        marginBottom: 4,
    },
    addressText: {
        fontSize: 13,
        fontFamily: 'DMSans_400Regular',
        color: '#666',
        lineHeight: 18,
    },
    addressCity: {
        fontSize: 13,
        fontFamily: 'DMSans_400Regular',
        color: '#666',
        marginTop: 2,
    },
    addressSubtext: {
        fontSize: 13,
        fontFamily: 'DMSans_400Regular',
        color: '#999',
        marginTop: 2,
    },
    moreButton: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 8,
    },
    // Modal styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    menuModal: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 8,
        minWidth: 150,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
    },
    menuText: {
        fontSize: 16,
        fontFamily: 'DMSans_500Medium',
        color: '#1A1A1A',
        marginLeft: 12,
    },
    menuDivider: {
        height: 1,
        backgroundColor: '#E8E8E8',
        marginVertical: 4,
    },
    confirmModal: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 24,
        width: '80%',
        maxWidth: 340,
    },
    confirmTitle: {
        fontSize: 20,
        fontFamily: 'DMSans_700Bold',
        color: '#1A1A1A',
        marginBottom: 12,
    },
    confirmText: {
        fontSize: 14,
        fontFamily: 'DMSans_400Regular',
        color: '#666',
        marginBottom: 24,
        lineHeight: 20,
    },
    confirmButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
    },
    cancelButtonText: {
        fontSize: 16,
        fontFamily: 'DMSans_700Bold',
        color: '#666',
    },
    deleteButton: {
        flex: 1,
        backgroundColor: '#FF4B4B',
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
    },
    deleteButtonText: {
        fontSize: 16,
        fontFamily: 'DMSans_700Bold',
        color: '#fff',
    },
    // Form styles
    formContainer: {
        flex: 1,
        backgroundColor: '#fff',
    },
    formHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
    },
    formTitle: {
        fontSize: 18,
        fontFamily: 'DMSans_700Bold',
        color: '#1A1A1A',
    },
    formScroll: {
        flex: 1,
    },
    formField: {
        paddingHorizontal: 20,
        marginTop: 20,
    },
    formLabel: {
        fontSize: 14,
        fontFamily: 'DMSans_700Bold',
        color: '#1A1A1A',
        marginBottom: 8,
    },
    formInput: {
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 14,
        fontFamily: 'DMSans_500Medium',
        color: '#333',
        backgroundColor: '#FAFAFA',
    },
    textArea: {
        height: 80,
        textAlignVertical: 'top',
    },
    saveButton: {
        backgroundColor: '#1F5E2E',
        paddingVertical: 16,
        borderRadius: 24,
        alignItems: 'center',
        marginHorizontal: 20,
        marginTop: 32,
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'DMSans_700Bold',
    },
});
